from django.urls import path
from .views import *
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', main, name='main'),
    path('crypto-binance', MyFormView.as_view(), name='crypto'),
    path('shares-twelvedata', SharesView.as_view(), name='shares'),
    path('process', process, name='process'),
    path('process_shares', process_shares, name='process_shares'),
    path('result', result, name='result'),
    path('check-task-status', check_task_status, name='check_task_status'),
    path('shares-polygon', SharesPolygonView.as_view(), name='shares_polygon'),
    path('shares-polygon-new', SharesPolygonNewView.as_view(), name='shares_polygon_new'),
    path('login', UserLoginView.as_view(), name='login'),
    path('profile', ProfileView.as_view(), name='profile'),
    path('change-password', change_password, name='change_password'),
    path('password-change/done/', password_change_done, name='password_change_done'),
    path('change-nickname', change_nickname, name='change_nickname'),
    path('logout/', auth_views.LogoutView.as_view(next_page='main'), name='logout'),
    path('profile/delete/<int:profile_id>/', delete_profile, name='delete_profile'),
    path('edit_profile/<int:profile_id>/', EditProfileView.as_view(), name='edit_profile'),
    path('trade', trade, name='trade'),
    path('cancel_task', cancel_task, name='cancel_task'),
    path('shares-yfinance', SharesYFinanceView.as_view(), name='shares_yfinance'),
    path('tradingview', TradingView.as_view(), name='tradingview'),
    path('ajax', ajax, name='ajax'),
    path('template-polygon', template_polygon, name='template_polygon'),
    path('template-twelvedata', template_twelvedata, name='template_twelvedata'),
    path('template-binance', template_binance, name='template_binance'),
    path('template-polygon/delete/<int:profile_id>/', delete_template_polygon, name='delete_template_polygon'),
    path('edit-template-polygon/<int:profile_id>/', edit_template_polygon_view, name='edit_template_polygon'),
    path('template-twelvedata/delete/<int:profile_id>/', delete_template_twelvedata, name='delete_template_twelvedata'),
    path('edit-template-twelvedata/<int:profile_id>/', EditTemplateTwelveDataView.as_view(), name='edit_template_twelvedata'),
    path('template-binance/delete/<int:profile_id>/', delete_template_binance, name='delete_template_binance'),
    path('edit-template-binance/<int:profile_id>/', EditTemplateBinanceView.as_view(), name='edit_template_binance'),    
]
